name: Deploy to AWS EC2 (ride-rent-stage)

on:
  push:
    branches:
      - development

jobs:
  deploy-Nextjs-Frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          sed -i 's/\r$//' ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Home Nextjs via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            echo "ðŸš€ Deploying Nextjs Home..."

            cd /home/ubuntu/ride-rent-home
            git fetch origin
            git checkout development || git checkout -b development origin/development
            git reset --hard origin/development

            docker compose down ride-rent-home || true
            docker compose -f docker-compose-dev.yml build --no-cache
            docker compose -f docker-compose-dev.yml up -d

            echo "âœ… Nextjs Home deployed successfully."
          EOF