name: Trigger GitLab CI/CD

on:
  push:
    branches:
      - development

jobs:
  trigger-gitlab-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitLab CI/CD Pipeline
        run: |
          curl -X POST https://gitlab.com/api/v4/projects/70348133/trigger/pipeline \
            -F token=glptt-e5565dc5a66ee87416132ec2ffc504b6ec71fcf3 \
            -F ref=development
